### ISSUE TITLE
TypeError: cannot pickle '_io.BufferedReader' object

### ISSUE THREAD

**Issue by SohaibAnwaar** [mdavis-xyz/lambda_multiprocessing#1]
Got this error, Used the same code as you written in readme
```
Traceback (most recent call last):
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sohaib/Documents/lukuku_workspace/navier_keywords/django-rest-boilerplate-main/navers/views/blog_exposure.py", line 161, in post
    response = p.map(self.get_blog_exposure, items)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 315, in map
    return self.starmap(func, zip(iterable), chunksize, callback, error_callback)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 325, in starmap
    results = self.starmap_async(func, iterable, chunksize, callback, error_callback)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 322, in starmap_async
    return [self.apply_async(func, args) for args in iterable]
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 322, in <listcomp>
    return [self.apply_async(func, args) for args in iterable]
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 309, in apply_async
    return c.submit(func, args, kwds)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 75, in submit
    self.parent_conn.send([(id, func, args, kwds), None])
  File "/home/sohaib/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/sohaib/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_io.BufferedReader' object
2022-07-26 21:18:16,027 ERROR Internal Server Error: /naver/blog-exposure/
Traceback (most recent call last):
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sohaib/Documents/lukuku_workspace/navier_keywords/django-rest-boilerplate-main/navers/views/blog_exposure.py", line 161, in post
    response = p.map(self.get_blog_exposure, items)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 315, in map
    return self.starmap(func, zip(iterable), chunksize, callback, error_callback)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 325, in starmap
    results = self.starmap_async(func, iterable, chunksize, callback, error_callback)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 322, in starmap_async
    return [self.apply_async(func, args) for args in iterable]
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 322, in <listcomp>
    return [self.apply_async(func, args) for args in iterable]
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 309, in apply_async
    return c.submit(func, args, kwds)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 75, in submit
    self.parent_conn.send([(id, func, args, kwds), None])
  File "/home/sohaib/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/sohaib/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_io.BufferedReader' object
```

**Comment by mdavis-xyz** [comment]
Hi,I'm on holiday for the next 6 weeks.  I won't be able to look into this for a while.Regards,Matt
-------- Original message --------From: Sohaib Anwaar ***@***.***> Date: 26/7/22  2:21 pm  (GMT+01:00) To: mdavis-xyz/lambda_multiprocessing ***@***.***> Cc: Subscribed ***@***.***> Subject: [mdavis-xyz/lambda_multiprocessing] TypeError: cannot pickle '_io.BufferedReader' object (Issue #1) 
Got this error, Used the same code as you written in readme
Traceback (most recent call last):
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sohaib/Documents/lukuku_workspace/navier_keywords/django-rest-boilerplate-main/navers/views/blog_exposure.py", line 161, in post
    response = p.map(self.get_blog_exposure, items)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 315, in map
    return self.starmap(func, zip(iterable), chunksize, callback, error_callback)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 325, in starmap
    results = self.starmap_async(func, iterable, chunksize, callback, error_callback)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 322, in starmap_async
    return [self.apply_async(func, args) for args in iterable]
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 322, in <listcomp>
    return [self.apply_async(func, args) for args in iterable]
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 309, in apply_async
    return c.submit(func, args, kwds)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 75, in submit
    self.parent_conn.send([(id, func, args, kwds), None])
  File "/home/sohaib/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/sohaib/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_io.BufferedReader' object
2022-07-26 21:18:16,027 ERROR Internal Server Error: /naver/blog-exposure/
Traceback (most recent call last):
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sohaib/Documents/lukuku_workspace/navier_keywords/django-rest-boilerplate-main/navers/views/blog_exposure.py", line 161, in post
    response = p.map(self.get_blog_exposure, items)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 315, in map
    return self.starmap(func, zip(iterable), chunksize, callback, error_callback)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 325, in starmap
    results = self.starmap_async(func, iterable, chunksize, callback, error_callback)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 322, in starmap_async
    return [self.apply_async(func, args) for args in iterable]
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 322, in <listcomp>
    return [self.apply_async(func, args) for args in iterable]
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 309, in apply_async
    return c.submit(func, args, kwds)
  File "/home/sohaib/.pyenv/versions/naver_keyword_pyenv/lib/python3.8/site-packages/lambda_multiprocessing/main.py", line 75, in submit
    self.parent_conn.send([(id, func, args, kwds), None])
  File "/home/sohaib/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/sohaib/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_io.BufferedReader' object

**Comment by mdavis-xyz** [comment]
I'm back now.

The function you're passing to multiprocessing, how was it defined?

Some things like lambdas (inline python functions, not AWS lambda) don't work well.

**Comment by mdavis-xyz** [comment]
Oh wait.

```
TypeError: cannot pickle '_io.BufferedReader' object
```

That looks like a problem with the arguments, not the function.
The normal multiprocessing library can't do this either.

```
from multiprocessing import Pool
from io import BytesIO, BufferedReader

def wr(f):
    return f.readline()

with BytesIO(b"startingtext") as bio:
    with BufferedReader(bio) as br:
        with Pool() as p:
            p.map(wr, [br])
```
```
Traceback (most recent call last):
  File "/home/matthew/Downloads/m.py", line 10, in <module>
    p.map(wr, [br])
  File "/home/matthew/.pyenv/versions/3.10.1/lib/python3.10/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/matthew/.pyenv/versions/3.10.1/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/matthew/.pyenv/versions/3.10.1/lib/python3.10/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/home/matthew/.pyenv/versions/3.10.1/lib/python3.10/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/matthew/.pyenv/versions/3.10.1/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_io.BufferedReader' object
```

If your arguments can't be pickled, you'll probably need to find another way to do what you're trying to do

**Comment by mdavis-xyz** [comment]
Closing this because this library's behaviour matches that of `multiprocessing.Pool`.
